### ISSUE TITLE
Database entries

### ISSUE THREAD

**Issue by vedeeva** [cse110-w21-group1/cse110-w21-group1#24]
- set up the auth for the Firebase
- array of note entries should be associated with each user

**Comment by eliasfang** [comment]
**Firebase Authentication**: https://firebase.google.com/docs/auth/web/start
- Add form to sign up new users
- Add form to sign in existing users
- Attach observer on each page to get user data
- Manage users (https://firebase.google.com/docs/auth/web/manage-users)
- Add password auth (https://firebase.google.com/docs/auth/web/password-auth)

**Comment by eliasfang** [comment]
**Firebase Realtime Database**: https://firebase.google.com/docs/database/web/start
- Create database on firebase
- Initialize with js sdk
- Structure data in json format (https://firebase.google.com/docs/database/web/structure-data)
- Add functions to read and write data (https://firebase.google.com/docs/database/web/read-and-write)
- Working with lists of data (https://firebase.google.com/docs/database/web/lists-of-data)
- Offline capabilities maybe? (https://firebase.google.com/docs/database/web/offline-capabilities)
